FROM node:latest
WORKDIR /app
COPY package*.json /app/
COPY src /app/src

RUN npm install && npm install ts-node typescript -g
RUN npm gerenerate
RUN npm build && npm start 
COPY . .

EXPOSE 3000
CMD ["npm", "run", "start", "dev"]