version: '3.8'
services:
server:
    container_name: server
    build:
        context: '.'
        target: base
    depends_on:
        - db
    db:
        image: postgres
        restart: always
        container_name: db
        ports:
          - "5432:5432"
        environment:
            POSTGRES_USER: postgres 
            POSTGRES_PASSWORD: 1242001Huan    
            POSTGRES_DB: student
volumes:
  pgdata: