version: '3.8'
services:
  db:
      image: postgres
      restart: always
      container_name: db
      ports:
        - "5432:5432"
      environment:
          POSTGRES_USER: postgres 
          POSTGRES_PASSWORD: 1242001Huan    
          POSTGRES_DB: student
      volumes: 
        - db-data:/var/lib/postgresql/data
volumes:
  db-data: